#!/bin/bash
# This script is for automating Raspberry Pi initial setup
#
# Script should be saved in /root/custom_setup
# remember to make it executable
# and put @reboot root /root/custom_setup_ubuntu in /etc/cron.d/custom_setup_ubuntu
#

new_hostname="new_pi"
new_username="matthew"
new_groupname=$new_username
new_password=$new_username

echo "Changing hostname to $new_hostname . . ."
echo $new_hostname > /etc/hostname

echo "Changing username to $new_username . . ."
usermod -l $new_username ubuntu
echo "Changing groupname to $new_groupname . . ."
groupmod --new-name $new_groupname ubuntu
echo "Changing home folder to /home/$new_username . . ."
usermod -d /home/$new_username -m $new_username
echo "Changing password to $new_password . . ."
echo "${new_username}:${new_password}" | chpasswd

echo "Reverting kernel network interface names to older default"
sed '$ s/$/ net.ifnames=0abc/' /boot/firmware/cmdline.txt

echo "Disabling Ubuntu sshd cloudinit customizations"
mv /etc/ssh/sshd_config.d/50-cloud-init.conf /etc/ssh/sshd_config.d/50-cloud-init.conf.disabled

echo "Adding WiFi entry to netplan"
echo "  wifis:
    wlan0:
      optional: true
      access-points:
        "Your_SSID_Here":
          password: "Your_Password_Here"
      dhcp4: true
" >> /etc/netplan/50-cloud-init.yaml

echo "Removing from rc.local . . ."
rm /etc/cron.d/custom_setup_ubuntu

echo "Rebooting."
init 6
