#!/bin/bash
# Created by: Matthew Miller
# 25OCT2015
# Adds IP to iptables blacklist

# NOTE: requires a iptables chain called "blacklist"
# Example: /etc/sysconfig/iptables
# *filter
# :INPUT ACCEPT [0:0]
# :FORWARD ACCEPT [0:0]
# :OUTPUT ACCEPT [0:0]
# :blacklist - [0:0]
# -A INPUT -j blacklist



for i in $@
do
        IP="$i"
        echo "Blacklisting $IP"
        iptables -A blacklist -s $IP -j DROP
done

echo ''
service iptables save
